export {};

const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const CURATOR_ID = 'classic-recipes-curator';

const recipes = [
  {
    title: 'Classic Pancakes',
    description: 'Fluffy buttermilk pancakes, golden on the outside and tender inside.',
    category: 'breakfast',
    cuisine: 'american',
    difficulty: 'easy',
    cookingTime: 20,
    prepTime: 10,
    totalTime: 30,
    servings: 4,
    calories: 350,
    protein: 9,
    carbs: 48,
    fat: 12,
    tags: ['vegetarian', 'classic', 'breakfast'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: false },
    isPremium: false,
    ingredients: [
      '1 1/2 cups all-purpose flour',
      '3 1/2 tsp baking powder',
      '1 tsp salt',
      '1 tbsp sugar',
      '1 1/4 cups milk',
      '1 egg',
      '3 tbsp melted butter',
      'Butter and maple syrup, to serve',
    ],
    instructions: [
      'Whisk together flour, baking powder, salt, and sugar in a large bowl.',
      'In a separate bowl, beat the egg, then mix in milk and melted butter.',
      'Pour the wet ingredients into the dry ingredients and whisk just until combined; do not overmix.',
      'Heat a lightly greased griddle or non-stick pan over medium heat.',
      'Pour 1/4 cup of batter per pancake and cook until bubbles form, about 2-3 minutes.',
      'Flip and cook until golden brown on the other side, about 1-2 minutes more.',
      'Serve warm with butter and maple syrup.',
    ],
  },
  {
    title: 'French Toast',
    description: 'Thick slices of bread soaked in a vanilla-spiced custard and pan-fried until golden.',
    category: 'breakfast',
    cuisine: 'french',
    difficulty: 'easy',
    cookingTime: 15,
    prepTime: 5,
    totalTime: 20,
    servings: 4,
    calories: 320,
    protein: 11,
    carbs: 38,
    fat: 13,
    tags: ['vegetarian', 'classic', 'breakfast'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: false },
    isPremium: false,
    ingredients: [
      '4 thick slices of brioche or challah bread',
      '2 large eggs',
      '1/2 cup milk',
      '1 tsp vanilla extract',
      '1/2 tsp cinnamon',
      'Pinch of salt',
      '2 tbsp butter, for frying',
      'Powdered sugar and maple syrup, to serve',
    ],
    instructions: [
      'Whisk together eggs, milk, vanilla, cinnamon, and salt in a shallow dish.',
      'Dip each bread slice into the mixture, soaking both sides for a few seconds.',
      'Melt butter in a skillet over medium heat.',
      'Cook each slice until golden brown, about 2-3 minutes per side.',
      'Dust with powdered sugar and serve with maple syrup.',
    ],
  },
  {
    title: 'Veggie Omelette',
    description: 'A light and fluffy three-egg omelette filled with sautéed peppers, onion, and cheese.',
    category: 'breakfast',
    cuisine: 'french',
    difficulty: 'easy',
    cookingTime: 10,
    prepTime: 10,
    totalTime: 20,
    servings: 1,
    calories: 310,
    protein: 21,
    carbs: 6,
    fat: 22,
    tags: ['vegetarian', 'gluten-free', 'breakfast'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: true },
    isPremium: false,
    ingredients: [
      '3 large eggs',
      '2 tbsp milk',
      'Salt and pepper to taste',
      '1 tbsp butter',
      '1/4 cup diced bell pepper',
      '1/4 cup diced onion',
      '1/4 cup shredded cheddar cheese',
    ],
    instructions: [
      'Whisk eggs with milk, salt, and pepper until well combined.',
      'Melt butter in a non-stick skillet over medium heat and sauté the pepper and onion until soft, about 3 minutes.',
      'Pour the egg mixture over the vegetables, tilting the pan to spread evenly.',
      'Cook until the edges set, then sprinkle cheese over half of the omelette.',
      'Fold in half and slide onto a plate to serve.',
    ],
  },
  {
    title: 'Shakshuka',
    description: 'Eggs poached in a spiced tomato and pepper sauce, a North African and Middle Eastern breakfast classic.',
    category: 'breakfast',
    cuisine: 'mediterranean',
    difficulty: 'medium',
    cookingTime: 30,
    prepTime: 10,
    totalTime: 40,
    servings: 4,
    calories: 280,
    protein: 14,
    carbs: 16,
    fat: 18,
    tags: ['vegetarian', 'gluten-free', 'spicy'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: true },
    isPremium: true,
    ingredients: [
      '3 tbsp olive oil',
      '1 onion, diced',
      '1 red bell pepper, diced',
      '3 cloves garlic, minced',
      '1 tsp cumin',
      '1 tsp paprika',
      '1/2 tsp chili flakes',
      '1 can (28 oz) crushed tomatoes',
      '6 large eggs',
      'Fresh parsley and feta, to garnish',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Heat olive oil in a large skillet and sauté onion and bell pepper until softened, about 5 minutes.',
      'Add garlic, cumin, paprika, and chili flakes, and cook for 1 minute until fragrant.',
      'Pour in the crushed tomatoes, season with salt and pepper, and simmer for 10-15 minutes until thickened.',
      'Make six small wells in the sauce and crack an egg into each.',
      'Cover and cook over low heat until the egg whites are set but yolks are still soft, about 8-10 minutes.',
      'Garnish with parsley and feta, and serve with crusty bread.',
    ],
  },
  {
    title: 'Caesar Salad',
    description: 'Crisp romaine lettuce tossed in a creamy garlic-anchovy dressing with parmesan and croutons.',
    category: 'lunch',
    cuisine: 'american',
    difficulty: 'easy',
    cookingTime: 15,
    prepTime: 15,
    totalTime: 30,
    servings: 4,
    calories: 290,
    protein: 9,
    carbs: 12,
    fat: 23,
    tags: ['classic', 'salad'],
    dietaryInfo: { isVegetarian: false, isVegan: false, isGlutenFree: false },
    isPremium: false,
    ingredients: [
      '2 heads romaine lettuce, chopped',
      '1 cup croutons',
      '1/2 cup grated parmesan cheese',
      '2 cloves garlic, minced',
      '2 anchovy fillets, minced',
      '1 egg yolk',
      '2 tbsp lemon juice',
      '1 tsp Dijon mustard',
      '1/2 cup olive oil',
      'Salt and black pepper to taste',
    ],
    instructions: [
      'Whisk garlic, anchovies, egg yolk, lemon juice, and Dijon mustard together in a bowl.',
      'Slowly drizzle in olive oil while whisking until the dressing is emulsified.',
      'Stir in half the parmesan and season with salt and pepper.',
      'Toss the romaine with the dressing until evenly coated.',
      'Top with croutons and remaining parmesan before serving.',
    ],
  },
  {
    title: 'Club Sandwich',
    description: 'A triple-decker sandwich layered with turkey, bacon, lettuce, tomato, and mayonnaise.',
    category: 'lunch',
    cuisine: 'american',
    difficulty: 'easy',
    cookingTime: 15,
    prepTime: 10,
    totalTime: 25,
    servings: 2,
    calories: 520,
    protein: 28,
    carbs: 38,
    fat: 28,
    tags: ['classic', 'sandwich'],
    dietaryInfo: { isVegetarian: false, isVegan: false, isGlutenFree: false },
    isPremium: false,
    ingredients: [
      '6 slices white or whole wheat bread, toasted',
      '4 tbsp mayonnaise',
      '6 slices bacon, cooked crisp',
      '6 oz sliced roasted turkey breast',
      '4 leaves lettuce',
      '1 large tomato, sliced',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Spread mayonnaise on one side of each slice of toasted bread.',
      'Layer turkey and a lettuce leaf on the first slice, then top with a second slice.',
      'Layer bacon and tomato slices on the second slice, season, then top with the third slice.',
      'Secure with toothpicks and slice diagonally into quarters.',
    ],
  },
  {
    title: 'Margherita Pizza',
    description: 'A simple Neapolitan pizza topped with San Marzano tomatoes, fresh mozzarella, and basil.',
    category: 'lunch',
    cuisine: 'italian',
    difficulty: 'medium',
    cookingTime: 15,
    prepTime: 90,
    totalTime: 105,
    servings: 4,
    calories: 380,
    protein: 16,
    carbs: 48,
    fat: 14,
    tags: ['vegetarian', 'classic', 'pizza'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: false },
    isPremium: false,
    ingredients: [
      '500g pizza dough',
      '1 cup crushed San Marzano tomatoes',
      '200g fresh mozzarella, torn',
      'Fresh basil leaves',
      '2 tbsp olive oil',
      '1 clove garlic, minced',
      'Salt to taste',
    ],
    instructions: [
      'Preheat oven to its highest setting (ideally 250°C/480°F) with a pizza stone or baking sheet inside.',
      'Stretch the dough into a round on a floured surface.',
      'Mix crushed tomatoes with garlic, olive oil, and a pinch of salt, then spread thinly over the dough.',
      'Scatter torn mozzarella over the top.',
      'Bake for 8-12 minutes until the crust is golden and the cheese is bubbling.',
      'Top with fresh basil leaves and a drizzle of olive oil before serving.',
    ],
  },
  {
    title: 'Minestrone Soup',
    description: 'A hearty Italian vegetable soup with beans and pasta in a tomato broth.',
    category: 'lunch',
    cuisine: 'italian',
    difficulty: 'medium',
    cookingTime: 45,
    prepTime: 15,
    totalTime: 60,
    servings: 6,
    calories: 220,
    protein: 9,
    carbs: 36,
    fat: 5,
    tags: ['vegetarian', 'soup', 'classic'],
    dietaryInfo: { isVegetarian: true, isVegan: true, isGlutenFree: false },
    isPremium: false,
    ingredients: [
      '2 tbsp olive oil',
      '1 onion, diced',
      '2 carrots, diced',
      '2 celery stalks, diced',
      '3 cloves garlic, minced',
      '1 can (14 oz) diced tomatoes',
      '6 cups vegetable broth',
      '1 can (14 oz) cannellini beans, drained',
      '1 cup small pasta (ditalini or elbow)',
      '2 cups chopped kale or spinach',
      'Salt, pepper, and grated parmesan, to taste',
    ],
    instructions: [
      'Heat olive oil in a large pot and sauté onion, carrots, and celery until softened, about 5 minutes.',
      'Add garlic and cook for 1 minute more.',
      'Stir in diced tomatoes and vegetable broth, then bring to a simmer.',
      'Add the cannellini beans and pasta, and cook until the pasta is tender, about 10 minutes.',
      'Stir in the kale or spinach and cook until wilted.',
      'Season with salt and pepper, and serve topped with grated parmesan.',
    ],
  },
  {
    title: 'Greek Salad',
    description: 'A refreshing salad of cucumber, tomato, red onion, olives, and feta dressed in olive oil and oregano.',
    category: 'lunch',
    cuisine: 'mediterranean',
    difficulty: 'easy',
    cookingTime: 0,
    prepTime: 15,
    totalTime: 15,
    servings: 4,
    calories: 220,
    protein: 6,
    carbs: 10,
    fat: 18,
    tags: ['vegetarian', 'gluten-free', 'salad'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: true },
    isPremium: false,
    ingredients: [
      '4 large tomatoes, cut into wedges',
      '1 cucumber, sliced',
      '1 red onion, thinly sliced',
      '1/2 cup Kalamata olives',
      '200g feta cheese, sliced or cubed',
      '1/4 cup olive oil',
      '1 tbsp red wine vinegar',
      '1 tsp dried oregano',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Combine tomatoes, cucumber, red onion, and olives in a large bowl.',
      'Whisk together olive oil, red wine vinegar, oregano, salt, and pepper.',
      'Pour the dressing over the vegetables and toss gently.',
      'Top with feta cheese and a sprinkle of extra oregano before serving.',
    ],
  },
  {
    title: 'Spaghetti Carbonara',
    description: 'A Roman pasta classic made with eggs, pecorino cheese, guanciale, and black pepper.',
    category: 'dinner',
    cuisine: 'italian',
    difficulty: 'medium',
    cookingTime: 25,
    prepTime: 10,
    totalTime: 35,
    servings: 4,
    calories: 560,
    protein: 25,
    carbs: 58,
    fat: 24,
    tags: ['classic', 'pasta'],
    dietaryInfo: { isVegetarian: false, isVegan: false, isGlutenFree: false },
    isPremium: false,
    ingredients: [
      '400g spaghetti',
      '150g guanciale or pancetta, diced',
      '4 large eggs',
      '100g pecorino romano, finely grated',
      '2 cloves garlic, lightly crushed (optional)',
      'Freshly ground black pepper',
      'Salt for pasta water',
    ],
    instructions: [
      'Bring a large pot of salted water to a boil and cook spaghetti until al dente.',
      'Meanwhile, render the guanciale in a skillet over medium heat until crisp.',
      'Whisk eggs with pecorino and plenty of black pepper in a bowl.',
      'Drain the pasta, reserving a cup of pasta water, and add the pasta to the skillet with the guanciale off the heat.',
      'Quickly stir in the egg mixture, adding splashes of pasta water until creamy and glossy.',
      'Serve immediately with extra pecorino and black pepper.',
    ],
  },
  {
    title: 'Chicken Tikka Masala',
    description: 'Marinated chicken pieces simmered in a creamy, spiced tomato curry sauce.',
    category: 'dinner',
    cuisine: 'indian',
    difficulty: 'medium',
    cookingTime: 40,
    prepTime: 30,
    totalTime: 70,
    servings: 4,
    calories: 480,
    protein: 34,
    carbs: 16,
    fat: 30,
    tags: ['gluten-free', 'curry', 'classic'],
    dietaryInfo: { isVegetarian: false, isVegan: false, isGlutenFree: true },
    isPremium: false,
    ingredients: [
      '700g boneless chicken thighs, cubed',
      '1 cup plain yogurt',
      '2 tbsp lemon juice',
      '2 tbsp garam masala',
      '1 tbsp ground cumin',
      '1 tbsp paprika',
      '4 cloves garlic, minced',
      '1 tbsp grated ginger',
      '2 tbsp butter or ghee',
      '1 onion, diced',
      '1 can (14 oz) tomato puree',
      '1 cup heavy cream',
      'Fresh cilantro, to garnish',
    ],
    instructions: [
      'Marinate the chicken in yogurt, lemon juice, half the garam masala, cumin, paprika, garlic, and ginger for at least 30 minutes.',
      'Sear the marinated chicken in a hot pan until lightly charred, then set aside.',
      'Melt butter in the same pan and sauté the onion until golden.',
      'Stir in the remaining garam masala and the tomato puree, and simmer for 10 minutes.',
      'Add the cream and cooked chicken, and simmer until the chicken is cooked through, about 10-15 minutes.',
      'Garnish with fresh cilantro and serve with rice or naan.',
    ],
  },
  {
    title: 'Pad Thai',
    description: 'Stir-fried rice noodles with shrimp, tofu, egg, and bean sprouts in a sweet-tangy tamarind sauce.',
    category: 'dinner',
    cuisine: 'thai',
    difficulty: 'medium',
    cookingTime: 20,
    prepTime: 20,
    totalTime: 40,
    servings: 4,
    calories: 430,
    protein: 22,
    carbs: 55,
    fat: 14,
    tags: ['classic', 'noodles'],
    dietaryInfo: { isVegetarian: false, isVegan: false, isGlutenFree: true },
    isPremium: false,
    ingredients: [
      '250g flat rice noodles',
      '2 tbsp vegetable oil',
      '200g shrimp, peeled and deveined',
      '100g firm tofu, cubed',
      '2 eggs',
      '3 tbsp tamarind paste',
      '3 tbsp fish sauce',
      '2 tbsp palm sugar or brown sugar',
      '2 cups bean sprouts',
      '3 green onions, chopped',
      '1/4 cup crushed peanuts',
      'Lime wedges, to serve',
    ],
    instructions: [
      'Soak the rice noodles in warm water until pliable, then drain.',
      'Heat oil in a wok and stir-fry the shrimp and tofu until the shrimp is pink, then push to one side.',
      'Crack the eggs into the wok and scramble briefly.',
      'Add the noodles, tamarind paste, fish sauce, and sugar, and toss to combine over high heat.',
      'Add bean sprouts and most of the green onions, and stir-fry for 1-2 minutes.',
      'Serve topped with crushed peanuts, remaining green onions, and lime wedges.',
    ],
  },
  {
    title: 'Beef Bourguignon',
    description: 'A rich French beef stew braised slowly in red wine with mushrooms, carrots, and pearl onions.',
    category: 'dinner',
    cuisine: 'french',
    difficulty: 'hard',
    cookingTime: 180,
    prepTime: 30,
    totalTime: 210,
    servings: 6,
    calories: 540,
    protein: 38,
    carbs: 18,
    fat: 28,
    tags: ['classic', 'stew', 'gluten-free'],
    dietaryInfo: { isVegetarian: false, isVegan: false, isGlutenFree: true },
    isPremium: true,
    ingredients: [
      '1.5kg beef chuck, cut into cubes',
      '200g bacon lardons',
      '1 bottle (750ml) red Burgundy wine',
      '2 cups beef stock',
      '2 tbsp tomato paste',
      '2 carrots, sliced',
      '1 onion, diced',
      '3 cloves garlic, minced',
      '500g pearl onions',
      '500g button mushrooms, halved',
      '2 tbsp flour',
      '2 sprigs fresh thyme and 1 bay leaf',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Brown the beef cubes in batches in a heavy pot, then set aside.',
      'Cook the bacon lardons in the same pot until crisp, then add the onion and carrots and sauté until softened.',
      'Stir in the garlic and flour, then return the beef to the pot.',
      'Pour in the red wine and beef stock, add the tomato paste, thyme, and bay leaf.',
      'Cover and simmer gently (or braise in a 160°C/325°F oven) for about 2.5-3 hours until the beef is fork-tender.',
      'In the last 30 minutes, sauté the pearl onions and mushrooms separately and stir them into the stew.',
      'Season to taste and serve with crusty bread or mashed potatoes.',
    ],
  },
  {
    title: 'Coq au Vin',
    description: 'Chicken braised in red wine with mushrooms, bacon, and pearl onions, a French bistro staple.',
    category: 'dinner',
    cuisine: 'french',
    difficulty: 'hard',
    cookingTime: 90,
    prepTime: 20,
    totalTime: 110,
    servings: 4,
    calories: 510,
    protein: 36,
    carbs: 12,
    fat: 30,
    tags: ['classic', 'gluten-free'],
    dietaryInfo: { isVegetarian: false, isVegan: false, isGlutenFree: true },
    isPremium: true,
    ingredients: [
      '8 chicken thighs and drumsticks',
      '150g bacon lardons',
      '1 bottle (750ml) red wine',
      '1 cup chicken stock',
      '2 tbsp tomato paste',
      '1 onion, diced',
      '3 cloves garlic, minced',
      '250g pearl onions',
      '250g button mushrooms, halved',
      '2 tbsp butter',
      '2 sprigs fresh thyme and 1 bay leaf',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Brown the chicken pieces in a large pot until golden, then set aside.',
      'Cook the bacon lardons in the same pot, then sauté the onion and garlic until softened.',
      'Return the chicken to the pot and pour in the red wine, chicken stock, and tomato paste.',
      'Add the thyme and bay leaf, cover, and simmer for about 45-60 minutes until the chicken is tender.',
      'Sauté the pearl onions and mushrooms in butter separately, then stir into the pot for the last 10 minutes.',
      'Season to taste and serve with crusty bread or buttered noodles.',
    ],
  },
  {
    title: 'Paella',
    description: 'A Spanish rice dish cooked with saffron, chicken, chorizo, and seafood in a wide shallow pan.',
    category: 'dinner',
    cuisine: 'mediterranean',
    difficulty: 'hard',
    cookingTime: 45,
    prepTime: 20,
    totalTime: 65,
    servings: 6,
    calories: 480,
    protein: 30,
    carbs: 52,
    fat: 16,
    tags: ['classic', 'gluten-free', 'seafood'],
    dietaryInfo: { isVegetarian: false, isVegan: false, isGlutenFree: true },
    isPremium: true,
    ingredients: [
      '3 tbsp olive oil',
      '400g chicken thighs, cut into pieces',
      '200g chorizo, sliced',
      '1 onion, diced',
      '1 red bell pepper, sliced',
      '3 cloves garlic, minced',
      '2 cups bomba or short-grain rice',
      'Pinch of saffron threads',
      '4 cups chicken or seafood stock',
      '300g mussels, cleaned',
      '300g shrimp, peeled',
      '1 cup frozen peas',
      'Lemon wedges, to serve',
    ],
    instructions: [
      'Heat olive oil in a paella pan and brown the chicken and chorizo, then set aside.',
      'Sauté the onion, bell pepper, and garlic in the same pan until softened.',
      'Stir in the rice and saffron, coating the grains in the oil and spices.',
      'Pour in the hot stock, return the chicken and chorizo to the pan, and simmer without stirring for about 15 minutes.',
      'Nestle the mussels and shrimp into the rice along with the peas, and cook for another 8-10 minutes until the rice is tender and the seafood is cooked.',
      'Let the paella rest for 5 minutes to develop a crust on the bottom, then serve with lemon wedges.',
    ],
  },
  {
    title: 'Ratatouille',
    description: 'A rustic Provençal stew of layered eggplant, zucchini, peppers, and tomatoes.',
    category: 'dinner',
    cuisine: 'french',
    difficulty: 'medium',
    cookingTime: 50,
    prepTime: 20,
    totalTime: 70,
    servings: 4,
    calories: 180,
    protein: 4,
    carbs: 22,
    fat: 10,
    tags: ['vegetarian', 'vegan', 'gluten-free'],
    dietaryInfo: { isVegetarian: true, isVegan: true, isGlutenFree: true },
    isPremium: false,
    ingredients: [
      '1 eggplant, diced',
      '2 zucchini, diced',
      '1 red bell pepper, diced',
      '1 yellow bell pepper, diced',
      '4 tomatoes, diced',
      '1 onion, diced',
      '4 cloves garlic, minced',
      '3 tbsp olive oil',
      '1 tsp dried thyme',
      '1 tsp dried herbes de Provence',
      'Salt and pepper to taste',
      'Fresh basil, to garnish',
    ],
    instructions: [
      'Heat olive oil in a large pot and sauté the onion and garlic until fragrant.',
      'Add the eggplant and cook for 5 minutes, then add the zucchini and bell peppers.',
      'Stir in the tomatoes, thyme, and herbes de Provence.',
      'Cover and simmer over low heat, stirring occasionally, until the vegetables are tender, about 30-35 minutes.',
      'Season with salt and pepper, garnish with fresh basil, and serve warm or at room temperature.',
    ],
  },
  {
    title: 'Tiramisu',
    description: 'A no-bake Italian dessert of espresso-soaked ladyfingers layered with mascarpone cream.',
    category: 'dessert',
    cuisine: 'italian',
    difficulty: 'medium',
    cookingTime: 0,
    prepTime: 30,
    totalTime: 270,
    servings: 8,
    calories: 420,
    protein: 7,
    carbs: 32,
    fat: 28,
    tags: ['vegetarian', 'classic', 'no-bake'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: false },
    isPremium: true,
    ingredients: [
      '6 egg yolks',
      '3/4 cup sugar',
      '500g mascarpone cheese',
      '1 1/2 cups strong brewed espresso, cooled',
      '2 tbsp coffee liqueur (optional)',
      '2 packs (about 400g) ladyfinger biscuits',
      '2 tbsp unsweetened cocoa powder',
    ],
    instructions: [
      'Whisk egg yolks and sugar in a heatproof bowl over simmering water until thick and pale, then cool slightly.',
      'Fold in the mascarpone until smooth and combined.',
      'Combine the espresso and coffee liqueur in a shallow dish.',
      'Quickly dip each ladyfinger into the espresso mixture and arrange in a layer in a serving dish.',
      'Spread half the mascarpone cream over the ladyfingers, then repeat with a second layer of soaked ladyfingers and cream.',
      'Dust generously with cocoa powder and refrigerate for at least 4 hours before serving.',
    ],
  },
  {
    title: 'Classic Apple Pie',
    description: 'A double-crusted pie filled with cinnamon-spiced apples, baked until golden and bubbling.',
    category: 'dessert',
    cuisine: 'american',
    difficulty: 'medium',
    cookingTime: 50,
    prepTime: 40,
    totalTime: 90,
    servings: 8,
    calories: 380,
    protein: 4,
    carbs: 56,
    fat: 16,
    tags: ['vegetarian', 'classic', 'baking'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: false },
    isPremium: false,
    ingredients: [
      '2 store-bought or homemade pie crusts',
      '6 cups peeled and sliced apples (Granny Smith or similar)',
      '3/4 cup sugar',
      '2 tbsp all-purpose flour',
      '1 tsp cinnamon',
      '1/4 tsp nutmeg',
      '1 tbsp lemon juice',
      '2 tbsp butter, cubed',
      '1 egg, beaten, for the wash',
    ],
    instructions: [
      'Preheat oven to 200°C (400°F) and line a pie dish with one crust.',
      'Toss the sliced apples with sugar, flour, cinnamon, nutmeg, and lemon juice.',
      'Pile the apple mixture into the crust and scatter the butter cubes on top.',
      'Cover with the second crust, seal and crimp the edges, and cut a few slits for venting.',
      'Brush the top with beaten egg and bake for 45-50 minutes until golden and the filling is bubbling.',
      'Cool for at least 20 minutes before slicing.',
    ],
  },
  {
    title: 'Chocolate Lava Cake',
    description: 'Individual chocolate cakes with a molten, gooey center, ready in minutes.',
    category: 'dessert',
    cuisine: 'french',
    difficulty: 'medium',
    cookingTime: 12,
    prepTime: 15,
    totalTime: 27,
    servings: 4,
    calories: 410,
    protein: 6,
    carbs: 38,
    fat: 26,
    tags: ['vegetarian', 'classic', 'chocolate'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: false },
    isPremium: false,
    ingredients: [
      '115g dark chocolate, chopped',
      '115g unsalted butter',
      '2 large eggs',
      '2 large egg yolks',
      '1/4 cup sugar',
      '2 tbsp all-purpose flour',
      'Butter and cocoa powder, for the ramekins',
    ],
    instructions: [
      'Preheat oven to 220°C (425°F) and butter and dust four ramekins with cocoa powder.',
      'Melt the chocolate and butter together until smooth.',
      'Whisk the eggs, egg yolks, and sugar until pale and slightly thickened.',
      'Fold in the melted chocolate, then fold in the flour until just combined.',
      'Divide the batter among the ramekins and bake for 10-12 minutes until the edges are set but the center is soft.',
      'Let rest for 1 minute, then invert onto plates and serve immediately.',
    ],
  },
  {
    title: 'Crème Brûlée',
    description: 'A silky vanilla custard topped with a brittle, caramelized sugar crust.',
    category: 'dessert',
    cuisine: 'french',
    difficulty: 'hard',
    cookingTime: 45,
    prepTime: 15,
    totalTime: 300,
    servings: 6,
    calories: 360,
    protein: 5,
    carbs: 26,
    fat: 27,
    tags: ['vegetarian', 'gluten-free', 'classic'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: true },
    isPremium: true,
    ingredients: [
      '2 cups heavy cream',
      '1 vanilla bean, split (or 2 tsp vanilla extract)',
      '5 egg yolks',
      '1/2 cup sugar, plus extra for the topping',
      'Pinch of salt',
    ],
    instructions: [
      'Preheat oven to 150°C (300°F) and place six ramekins in a deep baking dish.',
      'Heat the cream and vanilla bean in a saucepan until just simmering, then remove from heat and let steep for 10 minutes.',
      'Whisk egg yolks with sugar and salt until pale, then slowly whisk in the warm cream.',
      'Strain the custard and divide it among the ramekins.',
      'Add hot water to the baking dish to come halfway up the ramekins, and bake for 35-40 minutes until just set.',
      'Chill for at least 2 hours, then sprinkle sugar on top and caramelize with a kitchen torch or broiler before serving.',
    ],
  },
  {
    title: 'Hummus with Pita',
    description: 'A creamy chickpea and tahini dip, finished with olive oil and warm pita bread.',
    category: 'snack',
    cuisine: 'mediterranean',
    difficulty: 'easy',
    cookingTime: 0,
    prepTime: 10,
    totalTime: 10,
    servings: 6,
    calories: 210,
    protein: 7,
    carbs: 24,
    fat: 10,
    tags: ['vegetarian', 'vegan', 'dip'],
    dietaryInfo: { isVegetarian: true, isVegan: true, isGlutenFree: false },
    isPremium: false,
    ingredients: [
      '2 cans (14 oz each) chickpeas, drained, liquid reserved',
      '1/3 cup tahini',
      '3 tbsp lemon juice',
      '2 cloves garlic',
      '3 tbsp olive oil, plus extra to serve',
      '1/2 tsp ground cumin',
      'Salt to taste',
      'Pita bread and paprika, to serve',
    ],
    instructions: [
      'Combine chickpeas, tahini, lemon juice, garlic, olive oil, and cumin in a food processor.',
      'Blend until smooth, adding reserved chickpea liquid a tablespoon at a time to reach the desired consistency.',
      'Season with salt to taste.',
      'Spread onto a plate, drizzle with olive oil, and sprinkle with paprika.',
      'Serve with warm pita bread.',
    ],
  },
  {
    title: 'Bruschetta',
    description: 'Toasted bread topped with juicy tomatoes, basil, and garlic.',
    category: 'snack',
    cuisine: 'italian',
    difficulty: 'easy',
    cookingTime: 5,
    prepTime: 10,
    totalTime: 15,
    servings: 4,
    calories: 160,
    protein: 4,
    carbs: 20,
    fat: 7,
    tags: ['vegetarian', 'vegan', 'classic'],
    dietaryInfo: { isVegetarian: true, isVegan: true, isGlutenFree: false },
    isPremium: false,
    ingredients: [
      '1 baguette, sliced',
      '4 ripe tomatoes, diced',
      '2 cloves garlic, minced',
      '1/4 cup fresh basil, chopped',
      '3 tbsp olive oil',
      '1 tbsp balsamic vinegar',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Toast the baguette slices until golden and crisp.',
      'Combine tomatoes, garlic, basil, olive oil, and balsamic vinegar in a bowl.',
      'Season with salt and pepper.',
      'Spoon the tomato mixture onto the toasted bread just before serving.',
    ],
  },
  {
    title: 'Mango Lassi',
    description: 'A cooling Indian yogurt drink blended with sweet mango pulp and a touch of cardamom.',
    category: 'beverage',
    cuisine: 'indian',
    difficulty: 'easy',
    cookingTime: 0,
    prepTime: 5,
    totalTime: 5,
    servings: 2,
    calories: 180,
    protein: 6,
    carbs: 32,
    fat: 3,
    tags: ['vegetarian', 'gluten-free', 'drink'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: true },
    isPremium: false,
    ingredients: [
      '1 cup ripe mango pulp or chopped mango',
      '1 cup plain yogurt',
      '1/2 cup milk',
      '2 tbsp sugar, or to taste',
      'Pinch of ground cardamom',
      'Ice cubes',
    ],
    instructions: [
      'Combine mango, yogurt, milk, sugar, and cardamom in a blender.',
      'Blend until smooth and frothy.',
      'Pour over ice and serve immediately.',
    ],
  },
  {
    title: 'Hot Chocolate',
    description: 'Rich and creamy hot chocolate made with melted dark chocolate and warm milk.',
    category: 'beverage',
    cuisine: 'french',
    difficulty: 'easy',
    cookingTime: 10,
    prepTime: 5,
    totalTime: 15,
    servings: 2,
    calories: 280,
    protein: 8,
    carbs: 28,
    fat: 16,
    tags: ['vegetarian', 'classic', 'drink'],
    dietaryInfo: { isVegetarian: true, isVegan: false, isGlutenFree: true },
    isPremium: false,
    ingredients: [
      '2 cups whole milk',
      '100g dark chocolate, chopped',
      '1 tbsp sugar, or to taste',
      '1/2 tsp vanilla extract',
      'Whipped cream, to serve',
    ],
    instructions: [
      'Heat the milk in a saucepan over medium heat until steaming, but not boiling.',
      'Remove from heat and whisk in the chopped chocolate until fully melted and smooth.',
      'Stir in the sugar and vanilla extract.',
      'Pour into mugs and top with whipped cream before serving.',
    ],
  },
];

async function main() {
  console.log('Seeding classic recipes...');

  const curator = await prisma.user.upsert({
    where: { id: CURATOR_ID },
    update: {},
    create: {
      id: CURATOR_ID,
      email: 'curator@futurerecipes.app',
      name: 'FutureRecipes Curators',
      bio: 'Classic, time-tested recipes curated for the FutureRecipes community.',
      specialties: ['classic cuisine', 'baking', 'world cuisine'],
      dietaryPreferences: [],
    },
  });

  let created = 0;
  let skipped = 0;

  for (const recipeData of recipes) {
    const existing = await prisma.recipe.findFirst({
      where: { title: recipeData.title, authorId: curator.id },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await prisma.recipe.create({
      data: {
        ...recipeData,
        servings: recipeData.servings,
        status: 'published',
        isPublished: true,
        authorId: curator.id,
      },
    });
    created++;
    console.log(`Created classic recipe: ${recipeData.title}`);
  }

  console.log(`Classic recipe seeding complete. Created ${created}, skipped ${skipped} (already existed).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
